#!/bin/bash

source kernelenv

cd $LINUXSRCDIR

if [ "$1" == "configs" ]; then
	cd arch/arm/configs
	ls -1 *olympus*
	exit
fi

if [ "$1" == "clean" ]; then
	make clean
	exit
fi

if [ "$1" == "modules" ]; then
        make modules
        find . | grep "\.ko$"
        exit
fi

if [ "$1" != "" ]; then
	make $1
	exit
else
	make oldconfig
fi

if [ "$1" == "" ]; then
	make
	exit
fi

#cp arch/arm/boot/zImage ~/git_repos/atrix-mrom/cm_system/device/motorola/olympus/kernel
#cp arch/arm/mach-tegra/*.ko ~/git_repos/atrix-mrom/cm_system/device/motorola/olympus/modules
#cp drivers/scsi/scsi_wait_scan.ko ~/git_repos/atrix-mrom/cm_system/device/motorola/olympus/modules
#cp drivers/misc/vpndriver/vpnclient.ko ~/git_repos/atrix-mrom/cm_system/device/motorola/olympus/modules
